development:
  host: flagman.int
  base: dc=flagman,dc=int
  bind_dn: cn=phonebook,ou=Servers,dc=flagman,dc=int
  password: phonebook

test:
  host: 127.0.0.1
  base: dc=test,dc=local,dc=net
  bind_dn: cn=admin,dc=local,dc=net
  password: secret

production:
  host: flagman.int
  base: dc=flagman,dc=int
  bind_dn: cn=phonebook,ou=Servers,dc=flagman,dc=int
  password: phonebook
